### ISSUE TITLE
Added username password to conf file, but still able to connect with different username password

### ISSUE THREAD

**Issue by xerosanyam** [emqtt/emq-auth-username#26]
I placed a file  `/etc/emqttd/emq_auth_username.conf` with username password
like this:
auth.user.1.username = admin
auth.user.1.password = public

But there is no effect on the broker. It is still allowing unauthenticated username password.

Also made allow_anonymous false in `/etc/emqttd/emq.conf` .

**Comment by xerosanyam** [comment]
restart fixed the problem.

**Comment by raviypujar** [comment]
Hi,
Its still happening to me. Should i restart server ? or emq?
Whats the command
