### ISSUE TITLE
/emq-auth-username/etc/emq_auth_username.conf    Configuration invalid

### ISSUE THREAD

**Issue by wadeChen0915** [emqtt/emq-auth-username#47]
content:
auth.user.4.username = server
auth.user.4.password = 123456

auth.user.5.username = client
auth.user.5.password = 123456

auth.user.6.username = client1
auth.user.6.password = 123456

but i use ./bin/emqttd_ctl users add ,is work

**Comment by Gilbert-Wong** [comment]
Sorry, I don’t understand what you mean. Please give me more detailed information.
